version: "3.9"
services:

  app-blue:
    image: meu-registro/app:blue
    container_name: app-blue
    restart: always

  app-green:
    image: meu-registro/app:green
    container_name: app-green
    restart: always
    scale: 1

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app-blue
      - app-green
